---
- hosts: all

  vars:
    proxy_env:
      http_proxy: http://web-proxy.in.hpecorp.net:8080/

  tasks:
  - name: Install repositories packages
    file: dest=/ovoconfigure state=directory
    when: "ansible_distribution_major_version == '7' and ansible_distribution == 'RedHat'"
  - name: copy files
    copy: src=/LIN/OM-server/9.21/OML-9.21.tar dest=/ovoconfigure
